"""First-use acquisition for Pets recognition model artifacts.

The runtime prefers fixed, hash-verified release artifacts. When the DINOv2
TorchScript release URL is not configured, it can reproduce the checked-in
artifact from the manifest-pinned upstream revision and installs it only when
the generated bytes still match the manifest identity.
"""

from __future__ import annotations

import json
import tempfile
from pathlib import Path

from . import pipeline as pet_pipeline
from .errors import PetModelUnavailableError, PetRuntimeUnavailableError


def ensure_pet_model_artifacts(
    model_root: Path,
    *,
    allow_model_download: bool | None = None,
) -> bool:
    """Ensure missing Pets models are acquired before the first scan batch.

    Returns ``True`` when at least one artifact was installed. Downloads stay
    under ``model_root``; temporary Torch Hub files are also staged there and
    removed after the DINOv2 TorchScript artifact is produced.
    """

    allow_download = (
        pet_pipeline.pet_model_auto_download_enabled()
        if allow_model_download is None
        else bool(allow_model_download)
    )
    if not allow_download:
        return False

    root = Path(model_root)
    detector_manifest = pet_pipeline.PET_MODEL_MANIFEST["detector"]
    embedder_manifest = pet_pipeline.PET_MODEL_MANIFEST["embedder"]

    detector_path = root / Path(str(detector_manifest["filename"]))
    detector_missing = not detector_path.is_file()
    try:
        pet_pipeline.ensure_pet_detector_model(
            detector_path,
            allow_model_download=True,
        )
    except Exception as exc:  # noqa: BLE001 - normalize model acquisition errors
        raise PetModelUnavailableError(
            "Pet scanning unavailable: failed to acquire the YOLOX detector model "
            f"({_error_reason(exc)})."
        ) from exc

    embedder_path = root / Path(str(embedder_manifest["filename"]))
    embedder_missing = not embedder_path.is_file()
    if not embedder_missing:
        try:
            pet_pipeline._validate_dinov2_cache_metadata(
                embedder_path,
                model_name=str(embedder_manifest["model_name"]),
            )
            return detector_missing
        except (OSError, RuntimeError):
            _remove_dinov2_artifact(embedder_path)
            embedder_missing = True

    url = pet_pipeline.pet_embedder_model_url()
    if url:
        _download_dinov2_release(embedder_path, url=url)
    else:
        _bootstrap_dinov2_from_pinned_source(embedder_path)

    return detector_missing or embedder_missing


def _download_dinov2_release(model_path: Path, *, url: str) -> None:
    manifest = pet_pipeline.PET_MODEL_MANIFEST["embedder"]
    try:
        pet_pipeline._install_certifi_environment()
        pet_pipeline._download_file(
            url,
            model_path,
            label="DINOv2 TorchScript model",
            expected_sha256=str(manifest["torchscript_sha256"]),
            max_bytes=int(manifest["torchscript_size"]),
        )
        _write_dinov2_metadata(model_path)
        pet_pipeline._validate_dinov2_cache_metadata(
            model_path,
            model_name=str(manifest["model_name"]),
        )
    except Exception as exc:  # noqa: BLE001 - urllib/SSL/runtime failures vary
        _remove_dinov2_artifact(model_path)
        raise PetModelUnavailableError(
            "Pet scanning unavailable: failed to download the verified DINOv2 "
            f"TorchScript model from {url} ({_error_reason(exc)})."
        ) from exc


def _bootstrap_dinov2_from_pinned_source(model_path: Path) -> None:
    manifest = pet_pipeline.PET_MODEL_MANIFEST["embedder"]
    try:
        import torch
    except ImportError as exc:
        raise PetRuntimeUnavailableError(
            "Pet scanning unavailable: missing torch for DINOv2 model bootstrap. "
            'Install the optional Pets AI runtime with: pip install -e ".[pets-ai]"'
        ) from exc

    repository = str(manifest["source_repository"])
    revision = str(manifest["source_revision"])
    model_name = str(manifest["model_name"])
    source = f"{repository}:{revision}"
    expected_sha256 = str(manifest["torchscript_sha256"]).lower()
    expected_size = int(manifest["torchscript_size"])

    model_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        previous_hub_dir = torch.hub.get_dir()
    except Exception as exc:  # noqa: BLE001 - torch builds may differ
        raise PetRuntimeUnavailableError(
            "Pet scanning unavailable: PyTorch Hub is not available for DINOv2 "
            f"bootstrap ({_error_reason(exc)})."
        ) from exc

    try:
        with tempfile.TemporaryDirectory(
            prefix="iphoto-dinov2-bootstrap-",
            dir=model_path.parent,
        ) as temp_dir:
            temp_root = Path(temp_dir)
            torch.hub.set_dir(str(temp_root / "torch-hub"))
            candidate = temp_root / model_path.name
            with torch.random.fork_rng(devices=[]):
                torch.manual_seed(0)
                example = torch.randn(tuple(manifest["input_shape"]), dtype=torch.float32)
                eager_model = torch.hub.load(
                    source,
                    model_name,
                    source="github",
                    trust_repo=True,
                ).eval().cpu()
                with torch.no_grad():
                    eager_output = eager_model(example)
                    traced = torch.jit.trace(eager_model, example, strict=False)
                    traced.save(str(candidate))
                    scripted = torch.jit.load(str(candidate), map_location="cpu").eval()
                    scripted_output = scripted(example)

            if isinstance(eager_output, (list, tuple)):
                eager_output = eager_output[0]
            if isinstance(scripted_output, (list, tuple)):
                scripted_output = scripted_output[0]
            expected_shape = tuple(manifest["output_shape"])
            if tuple(scripted_output.shape) != expected_shape:
                raise RuntimeError(
                    "DINOv2 bootstrap output shape mismatch: "
                    f"{tuple(scripted_output.shape)} != {expected_shape}"
                )
            torch.testing.assert_close(scripted_output, eager_output, rtol=1e-4, atol=1e-5)

            artifact_sha256 = pet_pipeline._file_sha256(candidate)
            artifact_size = candidate.stat().st_size
            if artifact_sha256 != expected_sha256 or artifact_size != expected_size:
                raise RuntimeError(
                    "the pinned-source bootstrap did not reproduce the manifest artifact "
                    f"(sha256={artifact_sha256}, size={artifact_size}). Set "
                    f"{pet_pipeline.PET_EMBEDDER_MODEL_URL_ENV} to a mirror serving the "
                    "exact manifest-verified TorchScript artifact"
                )
            candidate.replace(model_path)
    except Exception as exc:  # noqa: BLE001 - torch/Torch Hub failures vary by version
        _remove_dinov2_artifact(model_path)
        raise PetModelUnavailableError(
            "Pet scanning unavailable: automatic DINOv2 acquisition from the pinned "
            f"source {source} failed ({_error_reason(exc)})."
        ) from exc
    finally:
        try:
            torch.hub.set_dir(previous_hub_dir)
        except Exception:
            pass

    try:
        _write_dinov2_metadata(model_path)
        pet_pipeline._validate_dinov2_cache_metadata(
            model_path,
            model_name=model_name,
        )
    except Exception as exc:  # noqa: BLE001 - normalize post-install validation failures
        _remove_dinov2_artifact(model_path)
        raise PetModelUnavailableError(
            "Pet scanning unavailable: the automatically acquired DINOv2 artifact "
            f"failed validation ({_error_reason(exc)})."
        ) from exc


def _write_dinov2_metadata(model_path: Path) -> None:
    manifest = pet_pipeline.PET_MODEL_MANIFEST["embedder"]
    metadata_path = pet_pipeline._dinov2_metadata_path(model_path)
    metadata_path.parent.mkdir(parents=True, exist_ok=True)
    metadata_path.write_text(
        json.dumps(
            {
                "model_name": manifest["model_name"],
                "source_repository": manifest["source_repository"],
                "source_revision": manifest["source_revision"],
                "torchscript_sha256": manifest["torchscript_sha256"],
                "torchscript_size": manifest["torchscript_size"],
                "input_shape": manifest["input_shape"],
                "output_shape": manifest["output_shape"],
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )


def _remove_dinov2_artifact(model_path: Path) -> None:
    try:
        Path(model_path).unlink(missing_ok=True)
        pet_pipeline._dinov2_metadata_path(model_path).unlink(missing_ok=True)
    except OSError:
        pass


def _error_reason(exc: Exception) -> str:
    return str(exc).strip() or exc.__class__.__name__
